### ISSUE TITLE
windows下log一直报这个怎么办

### ISSUE THREAD

**Issue by liuwangg** [LeonZYang/agent#3]
[Debug]2020/11/02 09:49:10 listening :1988
[Debug]2020/11/02 09:49:11 dial 127.0.0.1:6030 fail: dial tcp 127.0.0.1:6030: i/o timeout
[Debug]2020/11/02 09:49:14 dial 127.0.0.1:6030 fail: dial tcp 127.0.0.1:6030: i/o timeout

**Comment by LeonZYang** [comment]
127.0.0.1:6030是HBS的端口，看下HBS连接配置是否正确

**Comment by liuwangg** [comment]
> 127.0.0.1:6030是HBS的端口，看下HBS连接配置是否正确

谢谢大哥，就是连接配置出错了，改完了好用了！
